#ifndef FEATURE_LEVEL_DEFINES_H
#define FEATURE_LEVEL_DEFINES_H

#ifndef CPP11
	#if defined(__cplusplus) && __cplusplus >= 201103L
		#define CPP11 (1)
	#else
		#define CPP11 (0)
	#endif // defined(__cplusplus) && __cplusplus >= 201103L
#endif // CPP11

#if defined(_MSC_VER)

#define MSC_COMPILER (1)

#if (_MSC_VER >= 1800)
#define VS2013_FEATURE_LEVEL (1)
#define VS2012_FEATURE_LEVEL (1)
#define VS2010_FEATURE_LEVEL (1)
#elif (_MSC_VER >= 1700)
#define VS2013_FEATURE_LEVEL (0)
#define VS2012_FEATURE_LEVEL (1)
#define VS2010_FEATURE_LEVEL (1)
#elif (_MSC_VER >= 1600)
#define VS2013_FEATURE_LEVEL (0)
#define VS2012_FEATURE_LEVEL (0)
#define VS2010_FEATURE_LEVEL (1)
#else
#define VS2013_FEATURE_LEVEL (0)
#define VS2012_FEATURE_LEVEL (0)
#define VS2010_FEATURE_LEVEL (0)
#endif // !(_MSC_VER >= **)

#if VS2013_FEATURE_LEVEL
#define CPP_FEATURE_EXPLICIT_TYPE_CONV (1)
#define CPP_FEATURE_VARIADIC_TEMPLATES (1)
#define CPP_FEATURE_FUNCTION_DEFAULT (1)
#define CPP_FEATURE_FUNCTION_DELETION (1)
#endif // VS2013_FEATURE_LEVEL

#if VS2012_FEATURE_LEVEL
#define CPP_FEATURE_STRONGLY_TYPED_ENUMS (1)
#define CPP_FEATURE_FORWARD_DECLARED_ENUMS (1)
#define CPP_FEATURE_RANGE_BASED_LOOP (1)
#endif // VS2012_FEATURE_LEVEL

// Not Supported Yet: Damned Fools!
//#if (VS20 _FEATURE_LEVEL && CPP11)
//#define CPP_FEATURE_CONSTEXPR (1)
//#endif // 

//#if (VS20 _FEATURE_LEVEL && CPP11)
//#define CPP_FEATURE_USER_DEFINED_LITERALS (1)
//#endif // 

#else // if !defined(_MSC_VER)

#define MSC_COMPILER (0)
#define VS2013_FEATURE_LEVEL (0)
#define VS2012_FEATURE_LEVEL (0)
#define VS2010_FEATURE_LEVEL (0)

#if CPP11
#define CPP_FEATURE_EXPLICIT_TYPE_CONV (1)
#define CPP_FEATURE_VARADIC_TEMPLATES (1)
#define CPP_FEATURE_STRONGLY_TYPED_ENUMS (1)
#define CPP_FEATURE_FORWARD_DECLARED_ENUMS (1)
#define CPP_FEATURE_CONSTEXPR (1)
#define CPP_FEATURE_USER_DEFINED_LITERALS (1)
#define CPP_FEATURE_FUNCTION_DEFAULT (1)
#define CPP_FEATURE_FUNCTION_DELETION (1)
#define CPP_FEATURE_RANGE_BASED_LOOP (1)
#endif // CPP11

#endif // !defined(_MSC_VER)

#ifndef CPP_FEATURE_VARADIC_TEMPLATES
#define CPP_FEATURE_VARADIC_TEMPLATES (0)
#endif // CPP_FEATURE_VARADIC_TEMPLATES

#ifndef CPP_FEATURE_EXPLICIT_TYPE_CONV
#define CPP_FEATURE_EXPLICIT_TYPE_CONV (0)
#endif // CPP_FEATURE_EXPLICIT_TYPE_CONV

#ifndef CPP_FEATURE_STRONGLY_TYPED_ENUMS
#define CPP_FEATURE_STRONGLY_TYPED_ENUMS (0)
#endif // CPP_FEATURE_STRONGLY_TYPED_ENUMS

#ifndef CPP_FEATURE_FORWARD_DECLARED_ENUMS
#define CPP_FEATURE_FORWARD_DECLARED_ENUMS (0)
#endif // CPP_FEATURE_FORWARD_DECLARED_ENUMS

#ifndef CPP_FEATURE_CONSTEXPR
#define CPP_FEATURE_CONSTEXPR (0)
#endif // CPP_FEATURE_CONSTEXPR

#ifndef CPP_FEATURE_USER_DEFINED_LITERALS
#define CPP_FEATURE_USER_DEFINED_LITERALS (0)
#endif // CPP_FEATURE_USER_DEFINED_LITERALS

#ifndef CPP_FEATURE_FUNCTION_DEFAULT
#define CPP_FEATURE_FUNCTION_DEFAULT (0)
#endif // CPP_FEATURE_FUNCTION_DEFAULT

#ifndef CPP_FEATURE_FUNCTION_DELETION
#define CPP_FEATURE_FUNCTION_DELETION (0)
#endif // CPP_FEATURE_FUNCTION_DELETION

#ifndef CPP_FEATURE_RANGE_BASED_LOOP
#define CPP_FEATURE_RANGE_BASED_LOOP (0)
#endif // CPP_FEATURE_RANGE_BASED_LOOP

#endif // FEATURE_LEVEL_DEFINES_H